= Rotaract Club Finder
Rotaract Germany

ifdef::env-github[]
:tip-caption: 💡
:note-caption: ℹ
:important-caption: ❗
:caution-caption: 🔥
:warning-caption: ⚠
endif::[]

:badge_url: https://img.shields.io
:repo_path: rotaract/rotaract-club-finder

:year: 2023

// General Badges
image:{badge_url}/badge/Open_Source-❤-orange[Open Source, link="https://opensource.org"]
image:{badge_url}/badge/code_style-WordPress-brightgreen[Code Style, link="https://make.wordpress.org/core/handbook/best-practices/coding-standards/"]
image:https://img.shields.io/maintenance/yes/{year}[Maintenance Status] +
// Status Badges
image:https://github.com/{repo_path}/actions/workflows/build.yml/badge.svg[Build Plugin ZIP, link="https://github.com/{repo_path}/actions/workflows/build.yml"]

https://wordpress.org/[WordPress] plugin to find the nearest Rotaract Clubs.

== 🏗️ Setup

.🧰 Prerequisites
[NOTE]
--
* https://wordpress.com[WordPress] instance
* https://www.php.net[PHP] version 7.4.0 or higher
* https://getcomposer.org[Composer]
* https://nodejs.org[Node.js]
--

In order to either setup the environment for development or install plugin manually follow these steps.

. Install Composer Dependencies (add command option `--no-dev` if you do not need development tools)
+
[source]
----
composer install
----

== 🔧 Installation

.Prerequisites
[NOTE]
--
* https://wordpress.com[WordPress] instance
* https://www.php.net[PHP] version 7.4.0 or higher
--

IMPORTANT: The plugin's latest version is already installed at https://hosting.rotaract.de[Rotaract Hosting].

. Download https://github.com/rotaract/rotaract-club-finder/releases/latest/download/rotaract-club-finder.zip[ZIP file containing latest version]
. Install and activate plugin in your WordPress instance

== 🪛 Configuration

. Set Elastic API parameters in your `wp-config.php`
+
.snippet of `wp-config.php`
[source,php]
----
/**
 * Rotaract Params
 */
define( 'ROTARACT_CLUB_FINDER_CLOUD_ID', '<your-elastic-cloud-id>' );
define( 'ROTARACT_CLUB_FINDER_API_ID', '<your-elastic-api-id>' );
define( 'ROTARACT_CLUB_FINDER_API_KEY', '<your-elastic-api-key>' );
----
. Set Meilisearch Params in your `wp-config.php`
+
.snippet of `wp-config.php`
[source, php]
....
define( 'ROTARACT_MEILISEARCH_API_KEY', '<your-meiliseach-api-key>' );
define( 'ROTARACT_MEILISEARCH_URL', 'https://search.rotaract.de');
....
. Set OpenCage API key in your `wp-config.php`
+
.snippet of `wp-config.php`
[source, php]
....
define( 'OPENCAGE_API_KEY', '<your-opencage-api-key>' );
....

== Usage

. Add the shortcode `[rotaract-club-finder]` to a new or existing site that will insert the map.

== ⚖️ Legal Notices

Copyright © 2019 - {year}, Rotaract Deutschland

Licensed under European Union Public License 1.2 (EUPL-1.2).

_Rotary_, _Rotaract_, and _Interact_ are trademarks or registered trademarks of Rotary International and are used with the permission of Rotary International.
Other trademarks not owned by Rotary International are the property of their respective owners.
The license above does not grant any rights under trademark law and all such rights are reserved.
Modified versions must be renamed to avoid use of any Rotary International trademarks, including but not limited to _Rotary_, _Rotaract_, and _Interact_.

All Rotary, Rotaract, and Interact logos and graphics are under copyright.
