= Rotaract Club Finder
Rotaract Germany

ifdef::env-github[]
:tip-caption: 💡
:note-caption: ℹ
:important-caption: ❗
:caution-caption: 🔥
:warning-caption: ⚠
endif::[]
:devcontainer: 🐳

:badge_url: https://img.shields.io
:repo_path: rotaract/rotaract-club-finder

// General Badges
image:{badge_url}/badge/Open_Source-❤-orange[Open Source, link="https://opensource.org"]
image:{badge_url}/badge/code_style-WordPress-brightgreen[Code Style, link="https://make.wordpress.org/core/handbook/best-practices/coding-standards/"]
// Status Badges
image:https://github.com/{repo_path}/actions/workflows/build.yml/badge.svg[Build Plugin ZIP, link="https://github.com/{repo_path}/actions/workflows/build.yml"]

https://wordpress.org/[WordPress] plugin to find the nearest Rotaract clubs on an interactive map.

== 🔧 Installation

.Prerequisites
[NOTE]
--
* https://wordpress.com[WordPress] instance
* https://www.php.net[PHP] version 8.1 or higher (only use https://www.php.net/supported-versions.php[a supported version]
--

IMPORTANT: The plugin's latest version is already installed at https://hosting.rotaract.de[Rotaract Hosting].

. Download https://github.com/rotaract/rotaract-club-finder/releases/latest/download/rotaract-club-finder.zip[ZIP file containing latest version]
. https://wordpress.com/support/plugins/install-a-plugin/#install-a-plugin-with-a-zip-file[Install and activate plugin in WordPress]

== {devcontainer} Use Dev Container (VSCode)
. Install https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers[Dev Containers] extension in VSCode
. Clone the repository and open it in VSCode
. When the dialogue appears at the bottom right corner, click on `Reopen in Container`, if not the following key combination Mac: `Cmd + Shift + P` or Windows: `Ctrl + Shift + P` and type `Remote-Containers: Reopen in Container`
. Open wp-config.php with command `code ../../../wp-config.php ` and set the required configurations _(see Configuration)_
. Open Wordpress in your Browser on http://localhost:8080/

== 🪛 Configuration

. Set Meilisearch parameters in your `wp-config.php`
+
.snippet of `wp-config.php`
[source, php]
----
define( 'ROTARACT_CLUB_FINDER_MEILISEARCH_URL', 'https://meilisearch.rotaract.de' );
define( 'ROTARACT_CLUB_FINDER_MEILISEARCH_KEY', '<your-meiliseach-api-key>' );
define( 'ROTARACT_CLUB_FINDER_MEILISEARCH_SEARCHINDEX', 'Club');
----
  * The Meilisearch API key is required to have `search` permission on index `Club`
. Set OpenCage API key in your `wp-config.php`, used to convert geocode to geopoint data
+
.snippet of `wp-config.php`
[source, php]
----
define( 'OPENCAGE_API_KEY', '<your-opencage-api-key>' );
----
. Set Google Maps API key in your `wp-config.php`, used to display Google Maps
+
.snippet of `wp-config.php`
[source, php]
----
define( 'GOOGLE_MAPS_API_KEY', '<your-google-maps-api-key>' );
----

== 🪄 Usage

. Add the shortcode `[rotaract-club-finder]` to a new or existing site that will insert the map.

== ⚖️ Legal Notices

Copyright © 2019-2024, Rotaract Deutschland

Licensed under European Union Public License 1.2 (EUPL-1.2).

_Rotary_, _Rotaract_, and _Interact_ are trademarks or registered trademarks of Rotary International and are used with the permission of Rotary International.
Other trademarks not owned by Rotary International are the property of their respective owners.
The license above does not grant any rights under trademark law and all such rights are reserved.
Modified versions must be renamed to avoid use of any Rotary International trademarks, including but not limited to _Rotary_, _Rotaract_, and _Interact_.

All Rotary, Rotaract, and Interact logos and graphics are under copyright.
